version: "3.8"

services:
  order:
    build: ./order
    restart: always
    hostname: order
    container_name: order
    volumes:
      - ./order:/app/order
      # - /app/order/node_modules/
    env_file:
      - .env
    ports:
      - ${ORDER_PORT}:8000
      - ${ORDER_DEBUG_PORT}:9229
    networks:
      - setel
    depends_on:
      - redis
    command: yarn run start:debug

  payment:
    build: ./payment
    restart: always
    hostname: payment
    container_name: payment
    volumes:
      - ./payment:/app/payment
      # - /app/payment/node_modules/
    env_file:
      - .env
    ports:
      - ${PAYMENT_DEBUG_PORT}:9229
    networks:
      - setel
    depends_on:
      - redis
    command: yarn run start:debug

  redis:
    image: redis:alpine
    container_name: Redis
    hostname: redis
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - setel

networks:
  setel:
    driver: bridge
